---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-config
data:
  MODE: production
  PORT: "8080"
  DATABASE_URL: postgresql://postgres:password@postgres.cjeoakycezw4.us-east-1.rds.amazonaws.com:5432/postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        imagePullPolicy: Always
        image: gowrinth225/api-1.1:latest
        envFrom:
        - configMapRef:
            name: api-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  type: LoadBalancer
  selector:
    app: node-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
